spring.application.name=task-manager-backend


# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/taskmanager
spring.datasource.username=root
spring.datasource.password=monu2007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Firebase OAuth2 Resource Server Configuration
# TODO: Replace YOUR_FIREBASE_PROJECT_ID with your actual project ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/task-manager-838a6
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com