spring.application.name=task-manager-backend


# Server port (Render/Railway passes PORT env var)
server.port=${PORT:8080}

# Database connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/taskmanager}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:monu2007}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Firebase OAuth2 Resource Server Configuration
# TODO: Replace YOUR_FIREBASE_PROJECT_ID with your actual project ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/task-manager-838a6
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com