import { useState, useEffect } from 'react'
import './App.css'
import Reports from './Reports'

import { api } from './api'

function App() {
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    const loadTasks = async () => {
      try {
        const data = await api.getTasks();
        setTasks(data);
      } catch (error) {
        console.error("Failed to fetch tasks:", error);
      }
    };
    loadTasks();
  }, []);
  const [inputValue, setInputValue] = useState('')
  const [categoryValue, setCategoryValue] = useState('')
  const [priorityValue, setPriorityValue] = useState('Medium')
  const [viewMode, setViewMode] = useState('board') // 'board', 'reports'
  const getCurrentTimeframe = (tab) => {
    const now = new Date()
    if (tab === 'daily') {
      // YYYY-MM-DD for date input
      const year = now.getFullYear()
      const month = String(now.getMonth() + 1).padStart(2, '0')
      const day = String(now.getDate()).padStart(2, '0')
      return `${year}-${month}-${day}`
    }
    if (tab === 'monthly') {
      const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
      return months[now.getMonth()]
    }
    if (tab === 'yearly') {
      return now.getFullYear().toString()
    }
    return ''
  }

  const [activeTab, setActiveTab] = useState('daily') // 'daily', 'monthly', 'yearly'
  const [timeframeValue, setTimeframeValue] = useState(() => getCurrentTimeframe('daily'))
  const [isDarkMode, setIsDarkMode] = useState(() => {
    const saved = localStorage.getItem('darkMode')
    return saved ? JSON.parse(saved) : false
  })

  useEffect(() => {
    if (isDarkMode) {
      document.body.setAttribute('data-theme', 'dark')
    } else {
      document.body.removeAttribute('data-theme')
    }
    localStorage.setItem('darkMode', JSON.stringify(isDarkMode))
  }, [isDarkMode])


  const toggleDarkMode = () => setIsDarkMode(!isDarkMode)

  // Handle changing tabs to set default timeframe value
  const handleTabChange = (tab) => {
    setActiveTab(tab)
    setTimeframeValue(getCurrentTimeframe(tab))
  }

  const handleAddTask = async (e) => {
    e.preventDefault()
    if (!inputValue.trim() || !timeframeValue) return

    const newTask = {
      // id will be generated by the backend, but we can omit it or let backend handle it
      text: inputValue.trim(),
      type: activeTab,
      timeframe: timeframeValue,
      category: categoryValue.trim() || 'General',
      priority: priorityValue,
      status: 'todo', // 'todo', 'in-process', 'done'
      createdAt: new Date().toISOString(),
      completedAt: null
    }

    try {
      const createdTask = await api.createTask(newTask);
      setTasks([...tasks, createdTask]);
      setInputValue('')
      setCategoryValue('')
      setTimeframeValue(getCurrentTimeframe(activeTab))
    } catch (error) {
      console.error("Failed to create task:", error);
    }
  }

  const updateTaskStatus = async (id, newStatus) => {
    const completedAt = newStatus === 'done' ? new Date().toISOString() : null;
    try {
      await api.updateTask(id, { status: newStatus, completedAt });
      setTasks(
        tasks.map((task) => {
          if (task.id === id) {
            return { ...task, status: newStatus, completedAt };
          }
          return task;
        })
      )
    } catch (error) {
      console.error("Failed to update task:", error);
    }
  }

  const deleteTask = async (id) => {
    try {
      await api.deleteTask(id);
      setTasks(tasks.filter((task) => task.id !== id))
    } catch (error) {
      console.error("Failed to delete task:", error);
    }
  }

  const handleDragStart = (e, id) => {
    e.dataTransfer.setData('taskId', id)
  }

  const handleDragOver = (e) => {
    e.preventDefault()
  }

  const handleDrop = (e, status) => {
    const id = Number(e.dataTransfer.getData('taskId'))
    updateTaskStatus(id, status)
  }

  const renderTaskCard = (task) => (
    <div 
      key={task.id} 
      className="task-card"
      draggable
      onDragStart={(e) => handleDragStart(e, task.id)}
    >
      <div className="task-header">
        <span className={`type-badge ${task.type}-badge`}>
          {task.type === 'daily' ? new Date(task.timeframe).toLocaleDateString() : task.timeframe}
        </span>
        {task.priority && (
          <span className={`priority-badge priority-${task.priority.toLowerCase()}`}>
            {task.priority}
          </span>
        )}
      </div>
      <p className="task-text">{task.text}</p>
      
      <div className="task-actions">
        <div className="move-buttons">
          {/* Arrow buttons removed in favor of drag and drop */}
        </div>
        <button
          className="delete-btn"
          onClick={() => deleteTask(task.id)}
          title="Delete task"
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M3 6h18"></path>
            <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path>
            <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"></path>
          </svg>
        </button>
      </div>
    </div>
  )

  const activeTasks = tasks.filter(t => t.type === activeTab)
  const todoTasks = activeTasks.filter(t => t.status === 'todo')
  const inProcessTasks = activeTasks.filter(t => t.status === 'in-process')
  const doneTasks = activeTasks.filter(t => t.status === 'done')

  const getPlaceholderText = () => {
    switch (activeTab) {
      case 'daily': return 'What needs to be done today?'
      case 'monthly': return 'What is your target for this month?'
      case 'yearly': return 'What is your goal for this year?'
      default: return 'What needs to be done?'
    }
  }

  return (
    <div className="app-container">
      <header className="header">
        <div className="header-content">
          <h1>Workspace</h1>
          
          <div className="view-toggle">
            <button 
              className={`toggle-btn ${viewMode === 'board' ? 'active' : ''}`} 
              onClick={() => setViewMode('board')}
            >
              Board
            </button>
            <button 
              className={`toggle-btn ${viewMode === 'reports' ? 'active' : ''}`} 
              onClick={() => setViewMode('reports')}
            >
              Reports
            </button>
          </div>

          <button className="theme-toggle" onClick={toggleDarkMode} title="Toggle Dark Mode">
            {isDarkMode ? (
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>
            ) : (
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>
            )}
          </button>
        </div>
        <p>Organize your day, beautifully.</p>
      </header>

      <div className="tabs-container">
        <button 
          className={`tab-btn ${activeTab === 'daily' ? 'active' : ''}`}
          onClick={() => handleTabChange('daily')}
        >
          Daily Tasks
        </button>
        <button 
          className={`tab-btn ${activeTab === 'monthly' ? 'active' : ''}`}
          onClick={() => handleTabChange('monthly')}
        >
          Monthly Targets
        </button>
        <button 
          className={`tab-btn ${activeTab === 'yearly' ? 'active' : ''}`}
          onClick={() => handleTabChange('yearly')}
        >
          Yearly Goals
        </button>
      </div>

      {viewMode === 'reports' ? (
        <Reports tasks={tasks} activeTab={activeTab} handleTabChange={handleTabChange} />
      ) : (
        <>
          <form onSubmit={handleAddTask} className="add-task-container">
            <input
              type="text"
              className="task-input"
              placeholder={getPlaceholderText()}
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
            />
            <input
              type="text"
              className="timeframe-input"
              placeholder="Category (e.g. Work)"
              value={categoryValue}
              onChange={(e) => setCategoryValue(e.target.value)}
              style={{ width: '130px' }}
            />
            
            <select 
              className="timeframe-input" 
              value={priorityValue} 
              onChange={(e) => setPriorityValue(e.target.value)}
              style={{ width: '100px' }}
            >
              <option value="Low">Low</option>
              <option value="Medium">Medium</option>
              <option value="High">High</option>
            </select>
            
            {activeTab === 'daily' && (
              <input 
                type="date" 
                className="timeframe-input" 
                value={timeframeValue} 
                onChange={(e) => setTimeframeValue(e.target.value)}
                required
              />
            )}
            
            {activeTab === 'monthly' && (
              <select 
                className="timeframe-input" 
                value={timeframeValue} 
                onChange={(e) => setTimeframeValue(e.target.value)}
                required
              >
                <option value="" disabled>Select Month</option>
                {['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].map(month => (
                  <option key={month} value={month}>{month}</option>
                ))}
              </select>
            )}
            
            {activeTab === 'yearly' && (
              <input 
                type="number" 
                className="timeframe-input" 
                placeholder="Year (e.g. 2024)"
                value={timeframeValue} 
                onChange={(e) => setTimeframeValue(e.target.value)}
                required
                min="2024"
                max="2100"
              />
            )}

            <button 
              type="submit" 
              className="add-button"
              disabled={!inputValue.trim() || !timeframeValue}
            >
              Add
            </button>
          </form>

          <div className="board">
            <div 
              className="column todo"
              onDragOver={handleDragOver}
              onDrop={(e) => handleDrop(e, 'todo')}
            >
              <div className="column-header">
                To Do
                <span className="task-count">{todoTasks.length}</span>
              </div>
              <div className="task-list">
                {todoTasks.length === 0 ? (
                  <div className="empty-column">No tasks here</div>
                ) : (
                  todoTasks.map(renderTaskCard)
                )}
              </div>
            </div>

            <div 
              className="column in-process"
              onDragOver={handleDragOver}
              onDrop={(e) => handleDrop(e, 'in-process')}
            >
              <div className="column-header">
                In Process
                <span className="task-count">{inProcessTasks.length}</span>
              </div>
              <div className="task-list">
                {inProcessTasks.length === 0 ? (
                  <div className="empty-column">Nothing in process</div>
                ) : (
                  inProcessTasks.map(renderTaskCard)
                )}
              </div>
            </div>

            <div 
              className="column done"
              onDragOver={handleDragOver}
              onDrop={(e) => handleDrop(e, 'done')}
            >
              <div className="column-header">
                Done
                <span className="task-count">{doneTasks.length}</span>
              </div>
              <div className="task-list">
                {doneTasks.length === 0 ? (
                  <div className="empty-column">No completed tasks</div>
                ) : (
                  doneTasks.map(renderTaskCard)
                )}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  )
}

export default App
